// Batch up - auto-generated by runique
// Timestamp: 20260526_221257
// Tables: commande_lignes
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .drop_column(Alias::new("avec_legumes"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .drop_column(Alias::new("menu_enfant_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .drop_column(Alias::new("formule_jour_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .drop_column(Alias::new("menu_resto_id"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .add_column(ColumnDef::new(Alias::new("dessert_id")).integer().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .add_column(ColumnDef::new(Alias::new("entree_id")).integer().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("commande_lignes"))
                    .add_column(ColumnDef::new(Alias::new("menu_id")).integer().null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
