// Batch up - auto-generated by runique
// Timestamp: 20260526_221257
// Tables: plats
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("plats"))
                    .drop_column(Alias::new("avec_legumes"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("plats"))
                    .add_column(ColumnDef::new_with_type(Alias::new("usage"), ColumnType::Enum { name: Alias::new("UsagePlat").into_iden(), variants: vec![Alias::new("carte").into_iden(), Alias::new("menu").into_iden(), Alias::new("les_deux").into_iden()] }).not_null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
