server {
    listen 80;
    server_name test-itsuki.fr www.test-itsuki.fr;
    return 301 https://test-itsuki.fr$request_uri;
}

server {
    listen 443 ssl;
    server_name www.test-itsuki.fr;

    ssl_certificate     /etc/letsencrypt/live/test-itsuki.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/test-itsuki.fr/privkey.pem;

    return 301 https://test-itsuki.fr$request_uri;
}

server {
    listen 443 ssl;
    server_name test-itsuki.fr;

    ssl_certificate     /etc/letsencrypt/live/test-itsuki.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/test-itsuki.fr/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    server_tokens off;

    client_body_timeout   10s;
    client_header_timeout 10s;
    keepalive_timeout     65s;
    send_timeout          10s;
    client_max_body_size  10M;

    location /admin-campanile {
        limit_req zone=admin burst=5 nodelay;
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /media/ {
        alias /var/www/campanile/media/;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
        add_header X-Content-Type-Options "nosniff" always;
    }
}
