// Batch up - auto-generated by runique
// Timestamp: 20260526_221257
// Tables: menus
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("created_at"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("actif"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("stock"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("conditions"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("regime"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("theme"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("nb_personnes_min"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("prix_par_personne"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("titre"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("prix")).decimal().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new_with_type(Alias::new("type_menu"), ColumnType::Enum { name: Alias::new("TypeMenu").into_iden(), variants: vec![Alias::new("menu_resto").into_iden(), Alias::new("menu_enfant").into_iden(), Alias::new("formule_jour").into_iden()] }).not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("dessert_libre")).string().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("image")).string().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("entree_libre")).string().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("ordre")).integer().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("plat_libre")).string().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("nom")).string().not_null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
