// Batch down - auto-generated by runique
// Timestamp: 20260526_221257
// Tables: menus
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("prix"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("type_menu"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("dessert_libre"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("image"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("entree_libre"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("ordre"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("plat_libre"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .drop_column(Alias::new("nom"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("created_at")).date_time().not_null().default(Expr::current_timestamp()))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("actif")).boolean().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("stock")).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("conditions")).text().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new_with_type(Alias::new("regime"), ColumnType::Enum { name: Alias::new("RegimeMenu").into_iden(), variants: vec![Alias::new("standard").into_iden(), Alias::new("vegetarien").into_iden(), Alias::new("sans_gluten").into_iden(), Alias::new("halal").into_iden(), Alias::new("casher").into_iden()] }).not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new_with_type(Alias::new("theme"), ColumnType::Enum { name: Alias::new("ThemeMenu").into_iden(), variants: vec![Alias::new("mariage").into_iden(), Alias::new("bapteme").into_iden(), Alias::new("anniversaire").into_iden(), Alias::new("autre").into_iden()] }).not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("nb_personnes_min")).integer().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("prix_par_personne")).decimal().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("menus"))
                    .add_column(ColumnDef::new(Alias::new("titre")).string().not_null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
